### ISSUE TITLE
Add descriptions of what a sponsor and member is

### ISSUE THREAD

**Issue by kaspernissen** [cloud-native-nordics/cloud-native-nordics-website#10]
We need to make it explicit what a sponsor is and what a member is.

**Comment by jepp2078** [comment]
Sponsor description can be taken from here:

https://github.com/cloud-native-nordics/meetups/blob/master/SPONSOR_GUIDE.md

@luxas can maybe describe what a member is?

**Comment by luxas** [comment]
A member (I know the name is SUPER bad, pls suggest alternatives!) is a company that is part of our ecosystem (interested, attending meetups, aspiring, etc.), but has _not_ sponsored or spoken at a meetup. Basically, it's a way for us to collect companies in an aspiring group to-be-contacted for future meetups when we need speakers.

Also, it's a way for us to get a better insight into "who are interested in cloud native in my area" without _just_ considering "who was willing to work for promoting cloud native in my area".
Does this make sense? Totally, it should be documented, and renamed.
cc @netumoliver

**Comment by kaspernissen** [comment]
We have agreed that "Members" will be removed. Instead, sponsors will be modeled as different types of sponsors. 

Let's close this one for now to keep focus on the GoLive.
