### ISSUE TITLE
Add map with pins for each meetup group in the frontpage

### ISSUE THREAD

**Issue by kaspernissen** [cloud-native-nordics/cloud-native-nordics-website#14]
Would be cool with a section on the frontpage displaying a map of the nordics with a pin for each city.

We should be able to leverage the latitude and longitudes specified here: https://github.com/cloud-native-nordics/artwork/blob/master/slide-background/generator/places.js

**Comment by jepp2078** [comment]
I think we should fetch this data from the stats-api.

I created an issue in the artwork repository, that needs to be implemented before this can be done.

https://github.com/cloud-native-nordics/artwork/issues/12

**Comment by kaspernissen** [comment]
This is not relevant at the moment, as we have agreed to just use a simple static image as a start. I will close it for now.
