### ISSUE TITLE
Add section with stats on the frontpage

### ISSUE THREAD

**Issue by kaspernissen** [cloud-native-nordics/cloud-native-nordics-website#15]
Add section with stats on the frontpage. Basically visualizing the `stats.json` from the meetup repo.

**Comment by kevinunger** [comment]
I can do this. Would grab this issue ;)

**Comment by jepp2078** [comment]
Go ahead @kevinunger :-)

**Comment by kevinunger** [comment]
@jepp2078  Where is the `stats.json` ? Can't find it in the repo

**Comment by kaspernissen** [comment]
https://github.com/cloud-native-nordics/meetups/blob/master/stats.json

**Comment by kevinunger** [comment]
Ok, thanks!

**Comment by kaspernissen** [comment]
We should be way more explicit in defining the issues. Sorry about that.

**Comment by kaspernissen** [comment]
There's some ideas in this sideshow of the data that would be interesting to show (slide 4) https://docs.google.com/presentation/d/1ACD-CXJmPIse-tSkqye8yE-ioH44o4y5JO4s02aHVN8

Thank you for helping out btw 👏

**Comment by kevinunger** [comment]
Happy to help ;)

**Comment by kaspernissen** [comment]
This issue wasn't that well documented from the get go! My bad. 

I have created a new issue #31 with mockup and more description of how this should be implemented. 

@kevinunger Sorry for not being that clear. Hope we can use some of your work in PR https://github.com/cloud-native-nordics/cloud-native-nordics-website/pull/17 other places. E.g. having the stats on each groups details page, when this is implemented in #2
