### ISSUE TITLE
Actions using HCL format

### ISSUE THREAD

**Issue by vstirbu** [cloud-native-nordics/cloud-native-nordics-website#18]
This repo uses the HCL-based GitHub actions format [deprecated](https://help.github.com/en/articles/migrating-github-actions-from-hcl-syntax-to-yaml-syntax) on 30.09.2019.

The action should be migrated to the new format.

**Comment by Steiniche** [comment]
FYI this should be able to do automated by [the migration script](https://help.github.com/en/articles/migrating-github-actions-from-hcl-syntax-to-yaml-syntax#converting-workflow-files-in-your-repository-to-yaml-syntax).
