### ISSUE TITLE
Announce next meetups on the frontpage

### ISSUE THREAD

**Issue by hoeghh** [cloud-native-nordics/cloud-native-nordics-website#6]
It would be awesome to show the next upcoming events on the Frontpage, across all groups.

**Comment by jepp2078** [comment]
Yes @hoeghh, this is definitely something we want!

I think having something like this would be awesome: [carousel](https://vuetifyjs.com/en/components/carousels#playground)

We would need to be able to grab the image on the meetup, for it to be really awesome tho!

**Comment by kaspernissen** [comment]
This is visualized and described in more detail in #32. I will close this one for now.
